dataset_params:
  im_path: 'data/mnist/train/images'
  im_channels: 1
  im_size: 28
  name: 'mnist'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

ldm_params:
  down_channels : [128, 256, 256, 256]
  mid_channels : [256, 256]
  down_sample : [False, False, False]
  attn_down: [True, True, True]
  time_emb_dim : 256
  norm_channels: 32
  num_heads : 16
  conv_out_channels: 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  condition_config:
    condition_types: ['class']
    class_condition_config:
      num_classes: 10
      cond_drop_prob: 0.1


vae_params:
  z_channels: 3
  down_channels: [32, 64, 128]
  mid_channels: [128, 128]
  down_sample: [True, True]
  attn_down: [False, False]
  norm_channels: 32
  num_heads: 16
  num_down_layers: 1
  num_mid_layers: 1
  num_up_layers: 1

train_params:
  seed: 1111
  task_name: 'mnist'
  ldm_batch_size: 256
  vae_batch_size: 256
  disc_step_start: 235
  disc_weight: 0.5
  perceptual_weight: 1
  kl_weight: 0.000005
  ldm_epochs: 1000
  vae_epochs: 1000
  num_samples : 25
  num_grid_rows : 5
  ldm_lr: 0.00004
  vae_lr: 0.0001
  vae_acc_steps: 1
  vae_image_save_steps: 8
  save_latents: False
  cf_guidance_scale : 1.0
  vae_latent_dir_name: 'vae_latents'
  ldm_ckpt_name: 'cf_map_ldm_11.pth'
  ldm_best_ckpt_name: 'cf_map_best_ldm_11.pth'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt_cf.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt_cf.pth'
  vae_autoencoder_best_ckpt_name: 'vae_autoencoder_best_ckpt_cf.pth'
  vae_discriminator_best_ckpt_name: 'vae_discriminator_best_ckpt_cf.pth'
  classifier_batch_size: 256
  classifier_ckpt_name: 'classifier_ckpt.pth'
  mse_weight: 0.1
  cls_weight: 1.0
  cf_l1_weight: 0.2
  cf_l2_weight: 0.05
  cf_perceptual_weight: 0.01
  latent_dist_weight_1: 0.01
  latent_dist_weight_2: 0.001
  tv_weight: 0.02